-- MySQL Script generated by MySQL Workbench
-- Mon Jul 27 12:20:23 2020
-- Model: taxi_DB_model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ride_togather
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ride_togather
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ride_togather` DEFAULT CHARACTER SET utf8 ;
USE `ride_togather` ;

-- -----------------------------------------------------
-- Table `ride_togather`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ride_togather`.`users` (
  `user_no` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `user_type` INT(1) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `phone` CHAR(11) NOT NULL,
  `rated_times` INT NOT NULL,
  `rate_average` INT(3) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_no`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ride_togather`.`routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ride_togather`.`routes` (
  `route_no` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `departure_name` VARCHAR(45) NOT NULL,
  `departure_address` VARCHAR(45) NOT NULL,
  `destination_name` VARCHAR(45) NOT NULL,
  `destination_address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`route_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ride_togather`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ride_togather`.`post` (
  `post_no` INT NOT NULL AUTO_INCREMENT,
  `route_no` INT NOT NULL,
  `owner_user_no` INT NOT NULL,
  `reservation_time` TIMESTAMP NOT NULL,
  `attend_taxi_no` INT NULL,
  `attender_num` INT(2) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`post_no`),
  INDEX `fk_post_routes_idx` (`route_no` ASC),
  INDEX `fk_post_users1_idx` (`owner_user_no` ASC),
  CONSTRAINT `fk_post_routes`
    FOREIGN KEY (`route_no`)
    REFERENCES `ride_togather`.`routes` (`route_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_users1`
    FOREIGN KEY (`owner_user_no`)
    REFERENCES `ride_togather`.`users` (`user_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ride_togather`.`post_attender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ride_togather`.`post_attender` (
  `post_no` INT NOT NULL,
  `attender_user_no` INT NOT NULL,
  PRIMARY KEY (`post_no`),
  CONSTRAINT `fk_post_attender_post1`
    FOREIGN KEY (`post_no`)
    REFERENCES `ride_togather`.`post` (`post_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
